[project]
name        = "bitcoinworld-cont"
telemetry   = true
cache_dir   = "./.cache"
requirements = []

[editor]
auto-pairs = false

[networks]
local   = { url = "http://localhost:20443" }
testnet = { url = "https://stacks-node-api.testnet.stacks.co" }
mainnet = { url = "https://stacks-node-api.mainnet.stacks.co" }

# Trait SIP-010
[contracts.sip010-ft]
path = "contracts/sip010-ft.clar"
clarity_version = 2
epoch = "2.1"

# NUEVO: sbtc-v3
[contracts.sbtc-v3]
path       = "contracts/sbtc-v3.clar"
depends_on = ["sip010-ft"]
clarity_version = 2
epoch = "2.1"

# Market que llama a sbtc-v3
[contracts.market-factory-v3]
path       = "contracts/market-factory-v3.clar"
depends_on = ["sbtc-v3"]
clarity_version = 2
epoch = "2.1"
