[project]
name        = "bitcoinworld-cont"
telemetry   = true
cache_dir   = "./.cache"
requirements = []

[editor]
auto-pairs = false

[networks]
local   = { url = "http://localhost:20443" }
testnet = { url = "https://stacks-node-api.testnet.stacks.co" }
mainnet = { url = "https://stacks-node-api.mainnet.stacks.co" }

# Compile-time trait checker
[contracts.sip010-ft]
path = "contracts/sip010-ft.clar"
clarity_version = 2
epoch = "2.1"

# Our sbtc implementation
[contracts.sbtc-v2]
path       = "contracts/sbtc-v2.clar"
depends_on = ["sip010-ft"]
clarity_version = 2
epoch = "2.1"

# Market that calls into sbtc
[contracts.market-factory-v2]
path       = "contracts/market-factory-v2.clar"
depends_on = ["sbtc"]
clarity_version = 2
epoch = "2.1"
